spring:
  application:
    name: api-gateway

server:
  port: 7003

zuul:
  routes:
    cart:
      path: /cart/**
      serviceId: cart
      path: /guoauth2/**
      serviceId: guoauth2
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:7001/eureka/}