spring:
  application:
    name: api-gateway

server:
  port: 7003

zuul:
  routes:
    cart:
      path: /cart/**
      serviceId: cart

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/erureka/,http://eureka2:7002/eureka