spring:
  datasource:
      url: jdbc:mysql://39.107.90.7:3306/hai_store?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Mysqldba1!
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource

      initialSize: 1
      minIdle: 3
      maxActive: 20

      maxWait: 60000

      timeBetweenEvictionRunsMillis: 60000

      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

      filters: stat,wall,slf4j

      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  thymeleaf:
    prefix: classpath:/templates/
    model : HTML5
    encoding: UTF-8
    suffix: .html
    servlet:
      content-type: text/html
    cache: false



mybatis:
    type-aliases-package: com.giveu.guauth.entity
    mapper-locations: classpath:mapper/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger2
swagger2.package: cn.binux.cart.service

# Redis
redisKey:

  expire_time: 1800
  prefix:

    cart_info_profix: 'CART_INFO:'

    item_info_profix: 'ITEM_INFO:'
    item_info_base_suffix: ':BASE'
    item_info_desc_suffix: ':DESC'

    redis_cart_expire_time: 259200

yinhai:
  test:  test