spring:
  application:
    name: authclient
  redis:
    host: 39.107.90.7
    password: yinhai
    pool: 6379
  cloud:
    config:
      profile: prd
      uri: http://localhost:7005/

server:
   port: 7008


eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:7001/eureka/}

