spring:
  application:
    name:  guconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cruedfish/guConf/
          search-paths: central
          username: 1239128278@qq.com
          password: yinhai19941219
  http:
   encoding:
     charset: UTF-8
     force: true
     enabled: true
server:
  port: ${service.server.port:7005}
  tomcat:
    uri-encoding: UTF-8
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:7001/eureka/}