spring:
  application:
    name:  guconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cruedfish/guConf/
          search-paths: central
          username: 1239128278@qq.com
          password: yinhai19941219
server:
  port: 7004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/erureka/,http://localhost:7002/eureka